// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xmd5_hasher.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XMd5_hasher_CfgInitialize(XMd5_hasher *InstancePtr, XMd5_hasher_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XMd5_hasher_Start(XMd5_hasher *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMd5_hasher_ReadReg(InstancePtr->Axilites_BaseAddress, XMD5_HASHER_AXILITES_ADDR_AP_CTRL) & 0x80;
    XMd5_hasher_WriteReg(InstancePtr->Axilites_BaseAddress, XMD5_HASHER_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XMd5_hasher_IsDone(XMd5_hasher *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMd5_hasher_ReadReg(InstancePtr->Axilites_BaseAddress, XMD5_HASHER_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XMd5_hasher_IsIdle(XMd5_hasher *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMd5_hasher_ReadReg(InstancePtr->Axilites_BaseAddress, XMD5_HASHER_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XMd5_hasher_IsReady(XMd5_hasher *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMd5_hasher_ReadReg(InstancePtr->Axilites_BaseAddress, XMD5_HASHER_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XMd5_hasher_EnableAutoRestart(XMd5_hasher *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMd5_hasher_WriteReg(InstancePtr->Axilites_BaseAddress, XMD5_HASHER_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XMd5_hasher_DisableAutoRestart(XMd5_hasher *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMd5_hasher_WriteReg(InstancePtr->Axilites_BaseAddress, XMD5_HASHER_AXILITES_ADDR_AP_CTRL, 0);
}

void XMd5_hasher_Set_msgC(XMd5_hasher *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMd5_hasher_WriteReg(InstancePtr->Axilites_BaseAddress, XMD5_HASHER_AXILITES_ADDR_MSGC_DATA, Data);
}

u32 XMd5_hasher_Get_msgC(XMd5_hasher *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMd5_hasher_ReadReg(InstancePtr->Axilites_BaseAddress, XMD5_HASHER_AXILITES_ADDR_MSGC_DATA);
    return Data;
}

u32 XMd5_hasher_Get_x_BaseAddress(XMd5_hasher *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XMD5_HASHER_AXILITES_ADDR_X_BASE);
}

u32 XMd5_hasher_Get_x_HighAddress(XMd5_hasher *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XMD5_HASHER_AXILITES_ADDR_X_HIGH);
}

u32 XMd5_hasher_Get_x_TotalBytes(XMd5_hasher *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XMD5_HASHER_AXILITES_ADDR_X_HIGH - XMD5_HASHER_AXILITES_ADDR_X_BASE + 1);
}

u32 XMd5_hasher_Get_x_BitWidth(XMd5_hasher *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMD5_HASHER_AXILITES_WIDTH_X;
}

u32 XMd5_hasher_Get_x_Depth(XMd5_hasher *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMD5_HASHER_AXILITES_DEPTH_X;
}

u32 XMd5_hasher_Write_x_Words(XMd5_hasher *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XMD5_HASHER_AXILITES_ADDR_X_HIGH - XMD5_HASHER_AXILITES_ADDR_X_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Axilites_BaseAddress + XMD5_HASHER_AXILITES_ADDR_X_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XMd5_hasher_Read_x_Words(XMd5_hasher *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XMD5_HASHER_AXILITES_ADDR_X_HIGH - XMD5_HASHER_AXILITES_ADDR_X_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Axilites_BaseAddress + XMD5_HASHER_AXILITES_ADDR_X_BASE + (offset + i)*4);
    }
    return length;
}

u32 XMd5_hasher_Write_x_Bytes(XMd5_hasher *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XMD5_HASHER_AXILITES_ADDR_X_HIGH - XMD5_HASHER_AXILITES_ADDR_X_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Axilites_BaseAddress + XMD5_HASHER_AXILITES_ADDR_X_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XMd5_hasher_Read_x_Bytes(XMd5_hasher *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XMD5_HASHER_AXILITES_ADDR_X_HIGH - XMD5_HASHER_AXILITES_ADDR_X_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Axilites_BaseAddress + XMD5_HASHER_AXILITES_ADDR_X_BASE + offset + i);
    }
    return length;
}

void XMd5_hasher_InterruptGlobalEnable(XMd5_hasher *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMd5_hasher_WriteReg(InstancePtr->Axilites_BaseAddress, XMD5_HASHER_AXILITES_ADDR_GIE, 1);
}

void XMd5_hasher_InterruptGlobalDisable(XMd5_hasher *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMd5_hasher_WriteReg(InstancePtr->Axilites_BaseAddress, XMD5_HASHER_AXILITES_ADDR_GIE, 0);
}

void XMd5_hasher_InterruptEnable(XMd5_hasher *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMd5_hasher_ReadReg(InstancePtr->Axilites_BaseAddress, XMD5_HASHER_AXILITES_ADDR_IER);
    XMd5_hasher_WriteReg(InstancePtr->Axilites_BaseAddress, XMD5_HASHER_AXILITES_ADDR_IER, Register | Mask);
}

void XMd5_hasher_InterruptDisable(XMd5_hasher *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMd5_hasher_ReadReg(InstancePtr->Axilites_BaseAddress, XMD5_HASHER_AXILITES_ADDR_IER);
    XMd5_hasher_WriteReg(InstancePtr->Axilites_BaseAddress, XMD5_HASHER_AXILITES_ADDR_IER, Register & (~Mask));
}

void XMd5_hasher_InterruptClear(XMd5_hasher *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMd5_hasher_WriteReg(InstancePtr->Axilites_BaseAddress, XMD5_HASHER_AXILITES_ADDR_ISR, Mask);
}

u32 XMd5_hasher_InterruptGetEnabled(XMd5_hasher *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMd5_hasher_ReadReg(InstancePtr->Axilites_BaseAddress, XMD5_HASHER_AXILITES_ADDR_IER);
}

u32 XMd5_hasher_InterruptGetStatus(XMd5_hasher *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMd5_hasher_ReadReg(InstancePtr->Axilites_BaseAddress, XMD5_HASHER_AXILITES_ADDR_ISR);
}

