// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// AXILiteS
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x80 : Data signal of msgC
//        bit 7~0 - msgC[7:0] (Read/Write)
//        others  - reserved
// 0x84 : reserved
// 0x40 ~
// 0x7f : Memory 'x' (16 * 32b)
//        Word n : bit [31:0] - x[n]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XMD5_HASHER_AXILITES_ADDR_AP_CTRL   0x00
#define XMD5_HASHER_AXILITES_ADDR_GIE       0x04
#define XMD5_HASHER_AXILITES_ADDR_IER       0x08
#define XMD5_HASHER_AXILITES_ADDR_ISR       0x0c
#define XMD5_HASHER_AXILITES_ADDR_MSGC_DATA 0x80
#define XMD5_HASHER_AXILITES_BITS_MSGC_DATA 8
#define XMD5_HASHER_AXILITES_ADDR_X_BASE    0x40
#define XMD5_HASHER_AXILITES_ADDR_X_HIGH    0x7f
#define XMD5_HASHER_AXILITES_WIDTH_X        32
#define XMD5_HASHER_AXILITES_DEPTH_X        16

